development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 3000

test: &test
  adapter: postgresql
  database: test_twatter
  username: test_twatter
  password: beheer
  host: localhost
  encoding: UTF8

ci:
  <<: *test
